#   Configure file for pyKlock.py 
#   (c) Kevin Scott   Written Wednesday 31 December 2025  14:17:12
#
#   true and false are lower case 
#
[SETTINGS]
headers = [ "APPLICATION", "TIME", "MENU", "FONTS", "KLOCKS", "SOUNDS",]
appearanceModeTypes = [ "Light", "Dark", "System",]
colorThemeTypes = [ "green", "dark-blue", "blue",]

[INFO]
myVERSION = "2025.63"
myNAME = "pyKlock"

[APPLICATION]
appearanceMode = "Dark"
colorTheme = "dark-blue"
foreground = "#00ff00"
background = "#000000"
transparent = true
width = 300
height = 160
x_pos = 2684
y_pos = 148
Align_Right = true

[TIME]
type = "Fuzzy Time"
capitalise = true

[MENU]
visible = true

[TIME_FONT]
family = "It Lives In The Swamp BRK"
size = 50
weight = "normal"
slant = false
underline = false
overstrike = false

[STATUS_FONT]
family = "Default"
size = 12
weight = "normal"
slant = false
underline = false
overstrike = false

[KLOCKS]
vfd_width = 500
vfd_height = 260
vfd_x_pos = 108
vfd_y_pos = 108
vfd_foreground = "#82ccff"
vfd_background = "#000000"
binaryKlock_x_pos = 111
binaryKlock_y_pos = 100
textKlock_x_pos = 126
textKlock_y_pos = 100

[SOUNDS]
sounds = false
westminster = true
hour_chimes = true
quarter_chimes = true
hour_pips = false
cuckoo = false
sound_volume = 25

[EVENTS]
stage1Days = 5
stage2Days = 30
stage3Days = 30
stage1Colour = "red"
stage2Colour = "yellow"
stage3Colour = "green"
nowColour = "blue"
